from streamsight.splits.base_setting import Setting
from streamsight.splits.single_time_point_setting import SingleTimePointSetting
from streamsight.splits.sliding_window_setting import SlidingWindowSetting